# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'av', 'Available'), (b'na', 'Not Available')], default=b'av', max_length=2, verbose_name='Status')),
                ('eq_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type')),
                ('serial_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Serial Number')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type')),
                ('serial_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Serial Number')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simte.Equipment')),
            ],
        ),
    ]
