# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('in_type', models.CharField(choices=[(b'p', 'Preventive'), (b'f', 'Fix')], default=b'p', max_length=2, verbose_name='Type')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simte.Equipment')),
            ],
        ),
    ]
