# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simte', '0002_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(b'AV', 'Available'), (b'NA', 'Not Available')], default=b'AV', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='in_type',
            field=models.CharField(choices=[(b'P', 'Preventive'), (b'F', 'Fix')], default=b'P', max_length=2, verbose_name='Type'),
        ),
    ]
