# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simte', '0004_auto_20161112_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
    ]
