# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simte', '0006_administrator_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simte.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simte.Department', verbose_name='Department'),
        ),
    ]
