# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simte', '0008_auto_20161217_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(b'A', 'Available'), (b'U', 'Unavailable')], default=b'A', max_length=1, verbose_name='Status'),
        ),
    ]
